// <auto-generated />
namespace CashMachineApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _7hMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_7hMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211314304_7hMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
